spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bd_drink_bd
    username: user_prod
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # O "validate", "create", etc.
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

    # (Opcional) Timezone handling for MySQL
    jackson:
    time-zone: UTC

# (Opcional) Logging de SQL
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
